#####################
##  Oh My Zsh
#####################
.omz:
  type: archive
  url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 1h

.omz/custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 1h

.omz/custom/plugins/zsh-completions:
  type: archive
  url: https://github.com/zsh-users/zsh-completions/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 1h

.omz/custom/plugins/zsh-autosuggestions:
  type: archive
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 1h

.omz/custom/themes/powerlevel10k:
    type: archive
    url: https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz
    exact: true
    stripComponents: 1

#####################
##  Fonts
#####################
.local/share/fonts/CascadiaCode:                # 68MB
  type: archive
  format: zip
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/CascadiaCode.zip
.local/share/fonts/FantasqueSansMono:           # 9.8MB
  type: archive
  format: zip
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FantasqueSansMono.zip
.local/share/fonts/FiraCode:                    # 16.4MB
  type: archive
  format: zip
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraCode.zip
.local/share/fonts/Hasklig:                     # 75.7MB
  type: archive
  format: zip
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Hasklig.zip
.local/share/fonts/Iosevka:                     # 464MB
  type: archive
  format: zip
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Iosevka.zip
.local/share/fonts/VictorMono:                  # 48.4MB
  type: archive
  format: zip
  url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/VictorMono.zip
